language: python
python:
  - 2.7
install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap.py -c travis.cfg
  - bin/buildout -Nc travis.cfg
script:
  - bin/test
  - bin/coverage
after_success:
  - pip install coverage==3.6 coveralls
  - coveralls
notifications:
  email:
    - devs@imio.be
